apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: infra
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100